eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:1110/eureka/

# 服务注册中心端口号
server:
  port: 1112
spring:
  application:
    # 服务名称--调用的时候根据名称来调用该服务的方法
    name: service-consumer